# Generated by Django 2.2.4 on 2019-10-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_description',
        ),
    ]
