# Generated by Django 2.2.4 on 2019-10-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_product_p_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
